_wandb:
    value:
        cli_version: 0.21.3
        e:
            kruxu1t1fd24i4vwjddu8tj1ji9v6leu:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "7516192768"
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "427318710272"
                email: krseven@gmail.com
                executable: /Users/j/miniconda3/envs/mlflow-c8796fcdf2a60e9d2d7a0e2de87ce7cf78fe7920/bin/python
                git:
                    commit: 2356a92b84685532fe0ef2dbfd1ed7df7009e1dc
                    remote: git@github.com:kawgh1/udacity_ml_pipeline_genre_classification.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/download/download_data.py
                python: CPython 3.13.12
                root: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/download
                startedAt: "2026-02-12T12:21:49.672296Z"
                writerId: kruxu1t1fd24i4vwjddu8tj1ji9v6leu
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 2
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
