_wandb:
    value:
        cli_version: 0.21.3
        e:
            bwdkbuwo3f0rci8rhf4seyr5xn0kmzl2:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                args:
                    - --model_export
                    - model_export:latest
                    - --test_data
                    - data_test.csv:latest
                codePath: evaluate/run.py
                codePathLocal: run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "432869081088"
                email: krseven@gmail.com
                executable: /Users/j/miniconda3/envs/mlflow-08ff023f74d8dc4ccd988e8d53bd7b56325212db/bin/python
                git:
                    commit: 2356a92b84685532fe0ef2dbfd1ed7df7009e1dc
                    remote: git@github.com:kawgh1/udacity_ml_pipeline_genre_classification.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/evaluate/run.py
                python: CPython 3.13.12
                root: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/evaluate
                startedAt: "2026-02-12T12:40:45.154660Z"
                writerId: bwdkbuwo3f0rci8rhf4seyr5xn0kmzl2
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
