_wandb:
    value:
        cli_version: 0.21.3
        e:
            ds0qaul8530slu50irweaqaxiu4pjxuq:
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /Users/j/Desktop/udacity_ml_pipeline_genre_classification/outputs/2026-02-12/07-27-38/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                email: krseven@gmail.com
                executable: /Users/j/miniconda3/envs/mlflow-a3629828cd971ffe646011f938d3373bb5d5ef95/bin/python
                git:
                    commit: 2356a92b84685532fe0ef2dbfd1ed7df7009e1dc
                    remote: git@github.com:kawgh1/udacity_ml_pipeline_genre_classification.git
                host: MacBook-Pro.local
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/random_forest/run.py
                python: CPython 3.13.12
                root: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/random_forest
                startedAt: "2026-02-12T12:30:03.062028Z"
                writerId: ds0qaul8530slu50irweaqaxiu4pjxuq
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
