_wandb:
    value:
        cli_version: 0.21.3
        e:
            bboy7p8y9us6on6palrd9q75o03teyhl:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "8589934592"
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "432367280128"
                email: krseven@gmail.com
                executable: /Users/j/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/python3.13
                git:
                    commit: 2356a92b84685532fe0ef2dbfd1ed7df7009e1dc
                    remote: git@github.com:kawgh1/udacity_ml_pipeline_genre_classification.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/j/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/pytest
                python: CPython 3.13.12
                root: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/check_data
                startedAt: "2026-02-12T12:36:51.047230Z"
                writerId: bboy7p8y9us6on6palrd9q75o03teyhl
        m: []
        python_version: 3.13.12
        t:
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
