_wandb:
    value:
        cli_version: 0.21.3
        e:
            1b1oj667ylygmtosfv13405gjo7isq6p:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "7516192768"
                args:
                    - --input_artifact
                    - raw_data.parquet:latest
                    - --artifact_name
                    - preprocessed_data.csv
                    - --artifact_type
                    - preprocessed_data
                    - --artifact_description
                    - Data with preprocessing applied
                codePath: preprocess/run.py
                codePathLocal: run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "427460284416"
                email: krseven@gmail.com
                executable: /Users/j/miniconda3/envs/mlflow-428f3442275814dbf6350cf02d74496ce6bae3ac/bin/python
                git:
                    commit: 2356a92b84685532fe0ef2dbfd1ed7df7009e1dc
                    remote: git@github.com:kawgh1/udacity_ml_pipeline_genre_classification.git
                host: MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/preprocess/run.py
                python: CPython 3.13.12
                root: /Users/j/Desktop/udacity_ml_pipeline_genre_classification/preprocess
                startedAt: "2026-02-12T12:22:23.606565Z"
                writerId: 1b1oj667ylygmtosfv13405gjo7isq6p
        m: []
        python_version: 3.13.12
        t:
            "4": 3.13.12
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
